### ISSUE TITLE
 Utils- org.greenstand.android.TreeTracker.utilities.Utils.resizedImage(1 crash)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#101]
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:924)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:897)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
       at org.greenstand.android.TreeTracker.utilities.Utils.resizedImage(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.CameraActivity.galleryAddPic(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.CameraActivity.savePicture(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.CameraActivity.onPictureTaken(Unknown Source)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:997)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
[org.greenstand.android.treetracker_issue_27_crash_5B0E72C4025F000161DBF1149C8D6752_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2055847/org.greenstand.android.treetracker_issue_27_crash_5B0E72C4025F000161DBF1149C8D6752_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device1- Galaxy J1 Ace, OS- 4.4.4
App Version- Version 1.2.1 (31)
Fabric error- # 27

**Comment by deepwinter** [comment]
This error hasn't cropped back up, it's a single out of memory error and we have had hundreds of successful image uploads with resize, don't think this is an issue anymore.
