### ISSUE TITLE
MapsFragment-org.greenstand.android.TreeTracker.fragments.MapsFragment.onMapReady(7 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#106]
Fatal Exception: android.database.sqlite.SQLiteException: no such table: tree (code 1): , while compiling: select *, tree._id as tree_id from tree left outer join location on location_id = location._id where is_missing = 'N'
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1112)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:689)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
       at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1433)
       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1372)
       **at org.greenstand.android.TreeTracker.fragments.MapsFragment.onMapReady(Unknown Source)**
       at com.google.android.gms.maps.zzak.zza(Unknown Source)
       at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:361)
       **at et.b(:com.google.android.gms.DynamiteModulesB@11975034:20)**
       at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB@11975034:5)
       at com.google.maps.api.android.lib6.impl.bc.run(:com.google.android.gms.DynamiteModulesB@11975034:5)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_31_crash_5B3B77C7021D00017AECDD4E807C8FCD_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2164246/org.greenstand.android.treetracker_issue_31_crash_5B3B77C7021D00017AECDD4E807C8FCD_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device1- Galaxy J1 Ace, OS- 4.4.4
App Version- Version 1.2.1 (31)
Fabric error- # 31

**Comment by Surbhi79** [comment]
![issue106_device](https://user-images.githubusercontent.com/26098724/42296714-00a04d18-7fc7-11e8-8ec8-efb21948fb6b.PNG)

**Comment by deepwinter** [comment]
This crash indicates a missing .db file.  This is probably a path issue.

**Comment by deepwinter** [comment]
```
Hello Surbhi, unfortunately I believe your fix referenced below Introduced this bug.  You changed the name of the database being opened to a hardcoded value, while the database creator code itself uses the old value. 

commit c19edfa8e1cf574cd990656096656b09d5f089ce
Author: Surbhi79 <spate212@nyit.edu>
Date:   Tue Jun 12 18:47:25 2018 -0400

    Possible solution for #98
```
