### ISSUE TITLE
Crash on build 38

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#143]
Fabric Issue #55 

**After sign in, brought up the camara, pushed back and it crashed.**

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2884585, result=0, data=null} to activity {org.greenstand.android.TreeTracker.debug/org.greenstand.android.TreeTracker.activities.MainActivity}: 
kotlin.TypeCastException: null cannot be cast to non-null type android.widget.RelativeLayout
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4926)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4969)
       at android.app.ActivityThread.access$1600(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1850)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Fatal Exception: java.lang.RuntimeExceptionFailure delivering result ResultInfo{who=null, request=2884585, result=0, data=null} to activity {org.greenstand.android.TreeTracker.debug/org.greenstand.android.TreeTracker.activities.MainActivity}: kotlin.TypeCastException: null cannot be cast to non-null type android.widget.RelativeLayout Raw Text
--
  | android.app.ActivityThread.deliverResults (ActivityThread.java:4926)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

[org.greenstand.android.treetracker.debug_issue_55_crash_5BA172EF010600012F097B6DE68BC4FB_DNE_0_v2 (1).txt](https://github.com/Greenstand/treetracker-android/files/2395229/org.greenstand.android.treetracker.debug_issue_55_crash_5BA172EF010600012F097B6DE68BC4FB_DNE_0_v2.1.txt)

**Comment by Davidezrajay** [comment]
This one is going to the ice box
