### ISSUE TITLE
Crash build 38, Unable to start receiver

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#147]
Fabric Issue 57, http://crashes.to/s/6eeb4319281
3 Crashes, 2 Users

Fatal Exception: java.lang.RuntimeException: Unable to start receiver org.greenstand.android.TreeTracker.network.NetworkReceiver: kotlin.KotlinNullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2674)
       at android.app.ActivityThread.access$1700(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)

[org.greenstand.android.treetracker.debug_issue_57_crash_5BA46A83002B00013893AEEF2503B37D_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2412522/org.greenstand.android.treetracker.debug_issue_57_crash_5BA46A83002B00013893AEEF2503B37D_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
Fixed in fa2817ca9a136587ac1d35c5ff0a8f0f789d4a66
