### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#149]
Fabric Issue 59 http://crashes.to/s/b19dca51f76
Samsung: Operating systems 6 and 8 
Two crashes, Two users

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.greenstand.android.TreeTracker.debug/org.greenstand.android.TreeTracker.activities.MainActivity}: kotlin.KotlinNullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by kotlin.KotlinNullPointerException
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.<init>(MapsFragment.kt:67)
       at java.lang.Class.newInstance(Class.java)
       at android.support.v4.app.Fragment.instantiate(Fragment.java:434)
       at android.support.v4.app.FragmentState.instantiate(Fragment.java:109)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:2860)
       at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:149)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:328)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at org.greenstand.android.TreeTracker.activities.MainActivity.onCreate(MainActivity.kt:74)
       at android.app.Activity.performCreate(Activity.java:6877)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

[org.greenstand.android.treetracker.debug_issue_59_crash_5BA419A7027400013D036B8FD4BD713E_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2412629/org.greenstand.android.treetracker.debug_issue_59_crash_5BA419A7027400013D036B8FD4BD713E_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
When MainActivity is recreated, call to parent class onCreate attempts to restore state to fragments causes MapActivity to ask for dbHelper static var, which is only instantiated later in onCreate.

Poor legacy software design.
