### ISSUE TITLE
Attempt to invoke virtual method

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#150]
Fabric issue 60
3 Crashes, 1 User

http://crashes.to/s/851abb6312b

Samsung operating system 6 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.widget.Toast.<init>(Toast.java:144)
       at android.widget.Toast.makeText(Toast.java:456)
       at org.greenstand.android.TreeTracker.fragments.DataFragment$startDataSynchronization$1.doResume(DataFragment.kt:191)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
       at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

[org.greenstand.android.treetracker.debug_issue_60_crash_5BA419F000BF000141096B8FD4BD713E_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2412644/org.greenstand.android.treetracker.debug_issue_60_crash_5BA419F000BF000141096B8FD4BD713E_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
Appears to be a lifecycle issue, activity coroutine possibly asking for activity context after activity has been destroyed.
