### ISSUE TITLE
 android.database.sqlite.SQLiteException: no such table: tree 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#151]
Fabric Issue 61 
10 Crashes, 1 user

http://crashes.to/s/c3e1b72a98e

Google device: Operating system 9 (@Matt M.)

Fails when pressing the '+' button.
Fatal Exception: android.database.sqlite.SQLiteException: no such table: tree (code 1 SQLITE_ERROR): , while compiling: select *, tree._id as tree_id from tree left outer join location on location_id = location._id where is_missing = 'N'
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347)
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.onMapReady(MapsFragment.kt:422)
       at com.google.android.gms.maps.zzak.zza(Unknown Source:7)
       at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source:38)
       at android.os.Binder.transact(Binder.java:667)
       at fg.b(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):19)
       at com.google.android.gms.maps.internal.bg.a(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):5)
       at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):5)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

[org.greenstand.android.treetracker.debug_issue_61_crash_5BA430CA01D600017C1CB6ECB0314068_DNE_0_v2 (1).txt](https://github.com/Greenstand/treetracker-android/files/2412653/org.greenstand.android.treetracker.debug_issue_61_crash_5BA430CA01D600017C1CB6ECB0314068_DNE_0_v2.1.txt)

**Comment by deepwinter** [comment]
I believe this to be resolved by 

commit fa2817ca9a136587ac1d35c5ff0a8f0f789d4a66
Author: Matthew Xi <matthew.fullstackgis@gmail.com>
Date:   Tue Sep 25 13:59:04 2018 -0700

    Refactored database connection management to better follow application lifecycle. Fixes #149
