### ISSUE TITLE
Stuck on Camera

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#153]
It goes to the camera page, takes photos and goes directly back to the camera. Back button doesn't work. And it doesn't save the image.

**Comment by Davidezrajay** [comment]
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera.setPreviewSurface(Camera.java)
       at android.hardware.Camera.setPreviewDisplay(Camera.java:702)
       at org.greenstand.android.TreeTracker.camera.CameraPreview.surfaceCreated(CameraPreview.kt:135)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:712)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:316)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:10435)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7416)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


http://crashes.to/s/94d935961ee

**Comment by Davidezrajay** [comment]
Freezes on camera when camera is left open for
