### ISSUE TITLE
Fabric Issue 41

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#155]
This one is from some random phone: Huawei DRA-L-21... See phone specs below

[](http://phonedb.net/index.php?m=device&id=13578&c=huawei_y5_2018_dual_sim_lte_emea_dra-lx1__dra-l21)

[](http://crashes.to/s/e1af89be43f)

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.greenstand.android.TreeTracker/org.greenstand.android.TreeTracker.activities.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3884)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3053)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Caused by java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:438)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
       at org.greenstand.android.TreeTracker.database.DbHelper.createDataBase(DbHelper.kt:143)
       at org.greenstand.android.TreeTracker.application.TreeTrackerApplication.getDatabaseManager(TreeTrackerApplication.kt:47)
       at org.greenstand.android.TreeTracker.application.TreeTrackerApplication$Companion.getDatabaseManager(TreeTrackerApplication.kt:63)
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.onResume(MapsFragment.kt:93)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2294)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1387)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2991)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at android.app.Activity.performResume(Activity.java:7242)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3819)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3884)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3053)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Davidezrajay** [comment]
This one seems to no longer be an issue, can reopen if it pops up again
