### ISSUE TITLE
Fabric Issue #41, DbHelper.kt line 143

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#198]
Fabric Issus #41 http://crashes.to/s/e1af89be43f

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.greenstand.android.TreeTracker/org.greenstand.android.TreeTracker.activities.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3791)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Caused by java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:451)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
       at org.greenstand.android.TreeTracker.database.DbHelper.createDataBase(DbHelper.kt:143)
       at org.greenstand.android.TreeTracker.application.TreeTrackerApplication.getDatabaseManager(TreeTrackerApplication.kt:47)
       at org.greenstand.android.TreeTracker.application.TreeTrackerApplication$Companion.getDatabaseManager(TreeTrackerApplication.kt:63)
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.onResume(MapsFragment.kt:93)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2294)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1387)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2991)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at android.app.Activity.performResume(Activity.java:7112)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by Elforama** [comment]
Do we have any steps to reproduce this crash?

**Comment by Davidezrajay** [comment]
No occurrences within the last 30 days! This one seems to no longer be an issue. I'll reopen it if it comes back up. Thanks
