### ISSUE TITLE
Fabric Issue #44, DatabaseManager.QueryCursor

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#200]
http://crashes.to/s/3f35b359135

Fatal Exception: android.database.sqlite.SQLiteException: no such table: tree (code 1 SQLITE_ERROR): , while compiling: select *, tree._id as tree_id from tree left outer join location on location_id = location._id where is_missing = 'N'
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
       at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347)
       at org.greenstand.android.TreeTracker.database.DatabaseManager.queryCursor(DatabaseManager.kt:25)
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.onMapReady(MapsFragment.kt:428)
       at com.google.android.gms.maps.zzak.zza(Unknown Source:7)
       at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source:38)
       at android.os.Binder.transact(Binder.java:667)
       at fq.b(:com.google.android.gms.dynamite_mapsdynamite@14574083@14.5.74 (100408-219897028):15)
       at com.google.android.gms.maps.internal.bg.a(:com.google.android.gms.dynamite_mapsdynamite@14574083@14.5.74 (100408-219897028):4)
       at com.google.maps.api.android.lib6.impl.bj.run(:com.google.android.gms.dynamite_mapsdynamite@14574083@14.5.74 (100408-219897028):4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mozarty** [comment]
Fix : https://github.com/Greenstand/treetracker-android/pull/201
