### ISSUE TITLE
Fabric Issue #53,  DataFragment.kt line 151

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#223]
Link to Fabric issue: http://crashes.to/s/93fb1044e9f

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.widget.Toast.(Toast.java:107)
       at android.widget.Toast.makeText(Toast.java:265)
       at org.greenstand.android.TreeTracker.fragments.DataFragment$startDataSynchronization$1.doResume(DataFragment.kt:151)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:150)
       at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by deepwinter** [comment]
Looks like we are trying to create a toast against the wrong context, or against application context before it's available.

**Comment by Elforama** [comment]
This stacktrace is no longer relevant. I am not seeing this crash. Closing.
