### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#239]
-03-25 23:54:15.945 8766-9264/org.greenstand.android.TreeTracker.dev E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: org.greenstand.android.TreeTracker.dev, PID: 8766
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7983)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1392)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5426)
        at android.view.View.invalidateInternal(View.java:14959)
        at android.view.View.invalidate(View.java:14923)
        at android.view.View.invalidate(View.java:14907)
        at android.widget.TextView.checkForRelayout(TextView.java:8616)
        at android.widget.TextView.setText(TextView.java:5137)
        at android.widget.TextView.setText(TextView.java:4962)
        at android.widget.TextView.setText(TextView.java:4937)
        at org.greenstand.android.TreeTracker.fragments.DataFragment$updateData$1.invokeSuspend(DataFragment.kt:416)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by deepwinter** [comment]
@mozarty have any insight on this one ?

**Comment by Elforama** [comment]
This stack trace is no longer useful. This should be closed.

**Comment by tarekBondstein** [comment]
only the original thread that created a view hierarchy can touch its views kotlin coroutines sulation
