### ISSUE TITLE
App crashes when adding tree in digit flavor with thousands of trees

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#278]
2019-04-30 23:04:16.819 14601-14601/org.greenstand.android.TreeTracker.justdigit.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.greenstand.android.TreeTracker.justdigit.dev, PID: 14601
    android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:832)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
        at org.greenstand.android.TreeTracker.database.dao.NoteDao_Impl.insert(NoteDao_Impl.java:84)
        at org.greenstand.android.TreeTracker.managers.TreeManager.insertTreeNote(TreeManager.kt:110)
        at org.greenstand.android.TreeTracker.managers.TreeManager.addTree(TreeManager.kt:92)
        at org.greenstand.android.TreeTracker.viewmodels.TreeHeightViewModel$saveNewTree$1$invokeSuspend$$inlined$let$lambda$1.invokeSuspend(TreeHeightViewModel.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by deepwinter** [comment]
@Elforama This looks like it was related to inserting a note.

@Elforama In general can we have database errors get caught so that we don't crash?  If this is not related, it would have been better to continue and have a Fabric notification about the missed note, than to completely crash.

**Comment by Elforama** [comment]
This only happened to me after I added around 2k trees using the debug auto tree add method. 
Since we know about this crash, I don't think we should catch it, we should repro 100% and fix, else we're ignoring something bad.

**Comment by deepwinter** [comment]
I'm saying catch and report to Fabric.io, and give the user feedback on the issues rather than hard crashing when possible.

**Comment by maaudrana** [comment]
how can i download the app?for using in my android device

**Comment by sebastiangaertner** [comment]
Maaudrana. You can find it in the Google play store.  https://play.google.com/store/apps/details?id=org.greenstand.android.TreeTracker&hl=en_US

**Comment by dezidaisy** [comment]
Did you add a Commit statement after every DB transaction? This usually solves the issue.
db.beginTransaction();
  try {
    ...
    db.setTransactionSuccessful();
  } finally {
    db.endTransaction();
  }

**Comment by deepwinter** [comment]
@dezidaisy Are you saying that the root cause is a transaction issue, as in we may have had multiple inserts simultaneously causing the autoincrement not to update?  I haven't heard of that before in sqlite on Android, but sounds like it could be right here.

**Comment by dezidaisy** [comment]
I experienced this issue with multiple inserts with C# at work. Adding commit transaction solved the problem.
