### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteConstraintException

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#317]
The following bug is triggered by adding large number of trees using our debug feature.   Long pressing on 'add tree' in the dev or debug apps will add 500 random trees to the app.  Do this a few times and then try to add a single tree normally - this crash appears.

Build 1.2.6(81) 

Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
#################################################################
Error Code : 787 (SQLITE_CONSTRAINT_FOEIGNKEY)
Caused By : Abort due to constraint violation.
	(FOREIGN KEY constraint failed (code 787))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:953)
       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
       at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
       at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
       at org.greenstand.android.TreeTracker.database.dao.NoteDao_Impl.insert(NoteDao_Impl.java:84)
       at org.greenstand.android.TreeTracker.managers.TreeManager.insertTreeNote(TreeManager.kt:111)
       at org.greenstand.android.TreeTracker.managers.TreeManager.addTree(TreeManager.kt:93)
       at org.greenstand.android.TreeTracker.fragments.NewTreeFragment.saveToDb(NewTreeFragment.kt:268)
       at org.greenstand.android.TreeTracker.fragments.NewTreeFragment$onClick$1$1.invokeSuspend(NewTreeFragment.kt:174)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by deepwinter** [comment]
fixed in PR #352
