### ISSUE TITLE
Illegal state exception in TechnoF2

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#348]
From Crashlytics:

```
Fatal Exception: java.lang.IllegalStateException
Fragment NewTreeFragment{ef5afd8 (65506854-2adb-4454-8e0f-09f2ea443779)} not attached to an activity.

```

From Play store:

18 of this crash, 3 impacted users.  Just this device, must be a device specific fragment lifecycle issue.

Jun 18, 2:21 AM on app version 73
Tecno F2LTE (TECNO-F2LTE), Android 8.1
Report 1

java.lang.IllegalStateException: 
  at androidx.fragment.app.Fragment.requireActivity (Fragment.java:783)
  at org.greenstand.android.TreeTracker.fragments.NewTreeFragment$onClick$1.invokeSuspend (NewTreeFragment.java:176)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:233)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:888)

**Comment by arunbakt** [comment]
This issue is still relevant. I find 5 crashes in the last 30 days as of May 18 2020.

Fatal Exception: java.lang.IllegalStateException: Fragment NewTreeFragment{d1fac46 (87783397-9423-4380-be82-9f977dfed61d)} not associated with a fragment manager.
       at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:2)
       at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:3)
       at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:1)
       at org.greenstand.android.TreeTracker.fragments.NewTreeFragment$onClick$1.invokeSuspend(NewTreeFragment.kt:9)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:13)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
