### ISSUE TITLE
App crashes when adding many trees very quickly

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#413]
This issue is related to the cameraX library, bad internal thread management. We need to update to the latest cameraX library.

**Comment by arunbakt** [comment]
I believe the issue is related to the exception below. Due to the skipped frames log, I believe  a quick succession of "Add Tree" button clicks causes more than one onClick processing to take place when the current fragment is no longer  MapFragment causing the navigation controller invocation to navigate to `action_mapsFragment_to_new_tree_graph`  to throw `IllegalArgumentException`. This is because potentially the current fragment in the activity is already on NewTreeFragment.

I will raise a pull request with my changes to avoid triggering the onClick action on add tree button. I tested my changes and it seems to not crash the app as before.

```
I/Choreographer: Skipped 214 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@3a1e6cf[Toast]: MSG_RESIZED: frame=Rect(393, 1810 - 687, 1926) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/OpenGLRenderer: Davey! duration=3573ms; Flags=0, IntendedVsync=423962905314153, Vsync=423966471980677, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=423966472519147, AnimationStart=423966472548418, PerformTraversalsStart=423966472760085, DrawStart=423966473287428, SyncQueued=423966474168522, SyncStart=423966475382741, IssueDrawCommandsStart=423966477392012, SwapBuffers=423966479650033, FrameCompleted=423966480423522, DequeueBufferDuration=485000, QueueBufferDuration=393000, 
D/OpenGLRenderer: eglDestroySurface = 0x7a1e90a900, 0x7a21987000
D/ViewRootImpl@3a1e6cf[Toast]: dispatchDetachedFromWindow
D/ViewRootImpl@3a1e6cf[Toast]: Surface release. android.view.ViewRootImpl.doDie:7967 android.view.ViewRootImpl.die:7935 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.widget.Toast$TN.handleHide:1158 android.widget.Toast$TN$1.handleMessage:953 android.os.Handler.dispatchMessage:106 
D/InputTransport: Input channel destroyed: fd=91
D/MapsFragment: fab click
V/FA: Setting current screen to name, class: NewTreeFragment, MainActivity
V/FA: Recording user engagement, ms: 3942
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=387136124020539716, firebase_previous_screen(_pn)=MapsFragment, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=387136124020539717, firebase_screen(_sn)=NewTreeFragment}]
D/MapsFragment: fab click
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.greenstand.android.TreeTracker.dev, PID: 22273
    java.lang.IllegalArgumentException: navigation destination org.greenstand.android.TreeTracker.dev:id/action_mapsFragment_to_new_tree_graph is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:789)
        at androidx.navigation.NavController.navigate(NavController.java:730)
        at androidx.navigation.NavController.navigate(NavController.java:716)
        at androidx.navigation.NavController.navigate(NavController.java:907)
        at org.greenstand.android.TreeTracker.fragments.MapsFragment.onClick(MapsFragment.kt:155)
        at android.view.View.performClick(View.java:7346)
        at android.widget.TextView.performClick(TextView.java:14177)
        at android.view.View.performClickInternal(View.java:7312)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27794)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=3942, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=387136124020539716, firebase_screen(_sn)=MapsFragment}]
I/Process: Sending signal. PID: 22273 SIG: 9
Process 22273 terminated.
```

**Comment by arunbakt** [comment]
PR raised 
https://github.com/Greenstand/treetracker-android/pull/415/commits/eaaa3fbce5a430a3ada31aa40865d44ffc53d908

**Comment by Elforama** [comment]
Great work!
Fixed in: https://github.com/Greenstand/treetracker-android/pull/415
