### ISSUE TITLE
2 Crashes - Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called   

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#52]
at android.hardware.Camera.setPreviewSurface(Camera.java)
       at android.hardware.Camera.setPreviewDisplay(Camera.java:702)
       at org.greenstand.android.TreeTracker.camera.CameraPreview.surfaceCreated(CameraPreview.java:40)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:712)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:316)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:10435)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7416)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Davidezrajay** [comment]
[org.greenstand.android.treetracker.debug_issue_34_crash_5A99F2EB032500014EBF2E49E210C0FA_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1776964/org.greenstand.android.treetracker.debug_issue_34_crash_5A99F2EB032500014EBF2E49E210C0FA_DNE_0_v2.txt)

**Comment by Davidezrajay** [comment]
From Galaxy J1

**Comment by Davidezrajay** [comment]
Issue #8 on Fabric.io

**Comment by deepwinter** [comment]
I believe this has been resolved and is not longer relevant.  We don't see these crashes in the current builds.
