### ISSUE TITLE
Crash - Note Fragment jave line 324

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#55]
From a simulator?

[org.greenstand.android.treetracker.debug_issue_36_crash_5A9CD4F80282000109CFA643AA30CED4_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1782953/org.greenstand.android.treetracker.debug_issue_36_crash_5A9CD4F80282000109CFA643AA30CED4_DNE_0_v2.txt)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getAccuracy()' on a null object reference
       at org.greenstand.android.TreeTracker.fragments.NoteFragment.saveToDb(NoteFragment.java:324)
       at org.greenstand.android.TreeTracker.fragments.NoteFragment.onClick(NoteFragment.java:208)
       at android.view.View.performClick(View.java:5609)
       at android.view.View$PerformClick.run(View.java:22259)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getAccuracy()' on a null object reference
       at org.greenstand.android.TreeTracker.fragments.NoteFragment.saveToDb(NoteFragment.java:324)
       at org.greenstand.android.TreeTracker.fragments.NoteFragment.onClick(NoteFragment.java:208)
       at android.view.View.performClick(View.java:5609)
       at android.view.View$PerformClick.run(View.java:22259)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by deepwinter** [comment]
This isn't a currently supported feature.
