### ISSUE TITLE
14 Crashes - org.greenstand.android.TreeTracker.utilities.Utils.base64Image

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#59]
13 Crashes on Device: TECNO WX3

[org.greenstand.android.treetracker_issue_7_crash_5AAC8F850266000109546B1283A9D0EA_DNE_0_v2 (1).txt](https://github.com/Greenstand/treetracker-android/files/1823168/org.greenstand.android.treetracker_issue_7_crash_5AAC8F850266000109546B1283A9D0EA_DNE_0_v2.1.txt)

(https://fabric.io/greenstand/android/apps/org.greenstand.android.treetracker/issues/5aa2ced28cb3c2fa63aec36c?time=last-seven-days)

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.media.ExifInterface.getAttribute(java.lang.String)' on a null object reference
       at org.greenstand.android.TreeTracker.utilities.Utils.base64Image(Unknown Source)
       at org.greenstand.android.TreeTracker.api.SyncTask.doInBackground(Unknown Source)
       at org.greenstand.android.TreeTracker.api.SyncTask.doInBackground(Unknown Source)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by deepwinter** [comment]
We no longer send images as base64.  wont fix
