### ISSUE TITLE
 TreePreviewFragment-org.greenstand.android.TreeTracker.fragments.TreePreviewFragment.setPic (5 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#66]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.media.ExifInterface.getAttribute(java.lang.String)' on a null object reference
       at org.greenstand.android.TreeTracker.fragments.TreePreviewFragment.setPic(Unknown Source:111)
       at org.greenstand.android.TreeTracker.fragments.TreePreviewFragment.onCreateView(Unknown Source:157)
       at android.support.v4.app.Fragment.isSupportFragmentClass(Unknown Source:9)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:574)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source:32)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:50)
       at android.support.v4.app.BackStackRecord.addOp(Unknown Source:152)
       at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source:26)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:109)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Unknown Source:97)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source:2)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_11_crash_5AAD41A401CF00015AF9B939F48859D3_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1848844/org.greenstand.android.treetracker_issue_11_crash_5AAD41A401CF00015AF9B939F48859D3_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
The crash occurred on Samsung Galaxy S8 SM-G950F, Version 1.1.5 (20)
