### ISSUE TITLE
ForgotPasswordFragment  org.greenstand.android.TreeTracker.fragments.ForgotPasswordFragment.onCreateView (5 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#68]
Fatal Exception: java.lang.ClassCastException: org.greenstand.android.TreeTracker.activities.MainActivity cannot be cast to android.support.v7.app.ActionBarActivity
       at org.greenstand.android.TreeTracker.fragments.ForgotPasswordFragment.onCreateView(Unknown Source)
       at android.support.v4.app.Fragment.isSupportFragmentClass(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.addOp(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6284)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

**Comment by Surbhi79** [comment]
TECNO Camon CX: Version 7(OS)
App Version: 1.1.5 (20)
Fabric error # 9

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_9_crash_5AA6DD7601ED000113EFCEE06ADD5A3C_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1849008/org.greenstand.android.treetracker_issue_9_crash_5AA6DD7601ED000113EFCEE06ADD5A3C_DNE_0_v2.txt)

**Comment by beastlyCoder** [comment]
I have since fixed this issue. And it has been merged to the codebase.
