### ISSUE TITLE
MapsFragment org.greenstand.android.TreeTracker.fragments.MapsFragment.onMarkerClick(1 crash)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#69]
Fatal Exception: java.lang.NullPointerException
       at org.greenstand.android.TreeTracker.fragments.MapsFragment.onMarkerClick(Unknown Source)
       at com.google.android.gms.maps.zzb.zza(Unknown Source)
       at com.google.android.gms.maps.internal.zzas.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:361)
       at et.a(:com.google.android.gms.DynamiteModulesB@11975036:10)
       at com.google.android.gms.maps.internal.bh.a(:com.google.android.gms.DynamiteModulesB@11975036:5)
       at com.google.maps.api.android.lib6.impl.db.b(:com.google.android.gms.DynamiteModulesB@11975036:19)
       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.DynamiteModulesB@11975036:63)
       at com.google.maps.api.android.lib6.gmm6.vector.m.a(:com.google.android.gms.DynamiteModulesB@11975036:45)
       at com.google.maps.api.android.lib6.gmm6.vector.af.c(:com.google.android.gms.DynamiteModulesB@11975036:194)
       at com.google.maps.api.android.lib6.gmm6.vector.cr.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB@11975036:28)
       at com.google.maps.api.android.lib6.impl.gesture.h.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB@11975036:124)
       at com.google.maps.api.android.lib6.impl.gesture.d.handleMessage(:com.google.android.gms.DynamiteModulesB@11975036:26)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_10_crash_5AA2D7D8008F00012686E287AFFFC17B_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1848999/org.greenstand.android.treetracker_issue_10_crash_5AA2D7D8008F00012686E287AFFFC17B_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device- Galaxy K Zoom, OS- 4.4.2
App Version- Version 1.1.5 (20)
Fabric error- # 10

**Comment by deepwinter** [comment]
Not enough information to identify the error.
