### ISSUE TITLE
CameraPreview - org.greenstand.android.TreeTracker.camera.CameraPreview.(2 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#75]
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:3013)
       at org.greenstand.android.TreeTracker.camera.CameraPreview.(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.CameraActivity$OpenCameraTask.doInBackground(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.CameraActivity$OpenCameraTask.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6284)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_13_crash_5ACAFE44017F00013C74B56C483ABE81_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1905408/org.greenstand.android.treetracker_issue_13_crash_5ACAFE44017F00013C74B56C483ABE81_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device - TECNO Camon CX, O.S: 7.0
App Version- Version 1.1.5 (20)
Fabric issue # 13

**Comment by beastlyCoder** [comment]
Does this issue only come from this specific phone? I am not able to replicate this error on other O.S's and phones.

**Comment by Surbhi79** [comment]
@beastlyCoder  In the crash report, it is showing up for only this device. Well, actually it is difficult to even replicate the error on a somewhat closer emulator.

**Comment by deepwinter** [comment]
This could happen on a device that has no camera.
