### ISSUE TITLE
CameraActivity org.greenstand.android.TreeTracker.activities.CameraActivity.onClick

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#76]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.startPreview()' on a null object reference
       at org.greenstand.android.TreeTracker.activities.CameraActivity.onClick(Unknown Source)
       at android.view.View.performClick(View.java:6094)
       at android.view.View$PerformClick.run(View.java:23138)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6284)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_14_crash_5ACC64E300EC0001542AB56C483ABE81_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1905418/org.greenstand.android.treetracker_issue_14_crash_5ACC64E300EC0001542AB56C483ABE81_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device - TECNO Camon CX, O.S: 7.0
App Version- Version 1.1.5 (20)
Fabric issue # 14

**Comment by deepwinter** [comment]
Source code has been reorganized since this was logged.  No longer relevant.
