### ISSUE TITLE
Build 138 crashes on upload

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#791]
2022-02-21 11:23:57.515 8327-8372/org.greenstand.android.TreeTracker.test D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=878393650 in 21409ms(Backend next call timestamp 1645471458921). Attempt 1
2022-02-21 11:23:57.535 8327-8414/org.greenstand.android.TreeTracker.test E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: org.greenstand.android.TreeTracker.test, PID: 8327
    java.lang.IllegalStateException: Not implemented
        at androidx.work.CoroutineWorker.getForegroundInfo$suspendImpl(CoroutineWorker.kt:100)
        at androidx.work.CoroutineWorker.getForegroundInfo(Unknown Source:0)
        at androidx.work.CoroutineWorker$getForegroundInfoAsync$1.invokeSuspend(CoroutineWorker.kt:134)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by ZavenArra** [comment]
setExpedited is causing this crash

https://stackoverflow.com/questions/69627330/expedited-workrequests-require-a-listenableworker-to-provide-an-implementation-f

**Comment by ZavenArra** [comment]
This is a bug related to android 9 (see the stackoverflow thread).  Android 12 and above handle this for us, but to support older phones (which we absolutely must) it's necessary to add some extra code to handle the notification for the worker job.

**Comment by EngrTaofeek** [comment]
Fixed and pushed directly by Zaven.

**Comment by Elforama** [comment]
@ZavenArra was this fixed in your background sync worker update?

**Comment by ZavenArra** [comment]
yep
