### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Cannot round NaN value.

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#868]
From reading around this tends to be connected to setting visibility to View.GONE, or related to a bug in notifications lib/implementation. All crashes reported so far are on Samsung Galaxy Note9

Crash log follows, similar crashes mentioned at:
https://github.com/microg/GmsCore/issues/1309
https://github.com/markusressel/KodeEditor/issues/37

Reports from our tester seem to link this crash happens after taking a selfie, but only the first time.  Tester could add additional users afterword without any problem.   Crash persists in build 146.

```
Fatal Exception: java.lang.IllegalArgumentException: Cannot round NaN value.
       at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1132)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.populateAccessibilityNodeInfoProperties(AndroidComposeViewAccessibilityDelegateCompat.android.kt:705)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:371)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:113)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2391)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1321)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1331)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1234)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1032)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:341)
       at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:75)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1396)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by ZavenArra** [comment]
Possibly requires checking for an update to the compose library.
