### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant; on API level 25

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#902]
2022-03-09 16:04:28.937 19555-19555/[org.greenstand.android.TreeTracker.dev](http://org.greenstand.android.treetracker.dev/) E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.greenstand.android.TreeTracker.dev, PID: 19555
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:94)
        at org.greenstand.android.TreeTracker.utilities.TimeProvider.currentTime(TimeProvider.kt:11)
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater.saveNewDeviceConfig(DeviceConfigUpdater.kt:34)
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater.saveLatestConfig(DeviceConfigUpdater.kt:18)
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater$saveLatestConfig$1.invokeSuspend(DeviceConfigUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/org.greenstand.android.TreeTracker.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/org.greenstand.android.TreeTracker.dev-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:94) 
        at org.greenstand.android.TreeTracker.utilities.TimeProvider.currentTime(TimeProvider.kt:11) 
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater.saveNewDeviceConfig(DeviceConfigUpdater.kt:34) 
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater.saveLatestConfig(DeviceConfigUpdater.kt:18) 
        at org.greenstand.android.TreeTracker.models.DeviceConfigUpdater$saveLatestConfig$1.invokeSuspend(DeviceConfigUpdater.kt) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81) 
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41) 
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6816) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by ZavenArra** [comment]
https://github.com/Kotlin/kotlinx-datetime/issues/97 ?

**Comment by ZavenArra** [comment]
https://developer.android.com/studio/write/java8-support ?
