### ISSUE TITLE
Retrofit - retrofit2.Retrofit$Builder.baseUrl(2 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#91]
Fatal Exception: java.lang.IllegalArgumentException: baseUrl must end in /: https://206.189.207.26/api/mobile
       at retrofit2.Retrofit$Builder.baseUrl(Unknown Source)
       at retrofit2.Retrofit$Builder.baseUrl(Unknown Source)
       at org.greenstand.android.TreeTracker.api.Api.createApi(Unknown Source)
       at org.greenstand.android.TreeTracker.api.Api.getApi(Unknown Source)
       at org.greenstand.android.TreeTracker.fragments.SignupFragment.onClick(Unknown Source)
       at android.view.View.performClick(View.java:6308)
       at android.widget.TextView.performClick(TextView.java:11202)
       at android.view.View$PerformClick.run(View.java:23969)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_21_crash_5AEAD7C803530001545A306A9593D481_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1975734/org.greenstand.android.treetracker_issue_21_crash_5AEAD7C803530001545A306A9593D481_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device- Galaxy J3(2016), OS- 7.1.1
App Version- Version 1.2.1 (2)
Fabric error- # 21
