### ISSUE TITLE
DatabaseManager- org.greenstand.android.TreeTracker.database.DatabaseManager.queryCursor(9 crash)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#92]
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {org.greenstand.android.TreeTracker/org.greenstand.android.TreeTracker.activities.MainActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/org.greenstand.android.TreeTracker/databases/treetracker.db

Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/org.greenstand.android.TreeTracker/databases/treetracker.db
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1450)
       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1393)
       at org.greenstand.android.TreeTracker.database.DatabaseManager.queryCursor(Unknown Source)
       at org.greenstand.android.TreeTracker.fragments.DataFragment.updateData(Unknown Source)
       at org.greenstand.android.TreeTracker.fragments.DataFragment.onResume(Unknown Source)
       at android.support.v4.app.Fragment.performResume(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(Unknown Source)
       at android.support.v4.app.FragmentController.dispatchResume(Unknown Source)
       at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(Unknown Source)
       at android.support.v4.app.FragmentActivity.onPostResume(Unknown Source)
       at android.support.v7.app.AppCompatActivity.onPostResume(Unknown Source)
       at android.app.Activity.performResume(Activity.java:7017)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4146)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4251)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3362)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Surbhi79** [comment]
Device- Galaxy J1, OS- 6.0.1
App Version- Version 1.2.1 (31)
Fabric error- # 2

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_2_crash_5AF0ACBF00C1000137CE88270731C55C_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1981913/org.greenstand.android.treetracker_issue_2_crash_5AF0ACBF00C1000137CE88270731C55C_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
This is just the database open/close issue

**Comment by deepwinter** [comment]
Will be fixed in #116
