### ISSUE TITLE
DataFragment (Deobfuscated class name) org.greenstand.android.TreeTracker.fragments.DataFragment.onPostExecute

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#93]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.widget.Toast.(Toast.java:102)
       at android.widget.Toast.makeText(Toast.java:260)
       at org.greenstand.android.TreeTracker.fragments.DataFragment.onPostExecute(Unknown Source)
       at org.greenstand.android.TreeTracker.managers.SyncTask.doInBackground(Unknown Source)
       at org.greenstand.android.TreeTracker.managers.SyncTask.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_22_crash_5AEE8BAE02C0000150B41ADADD100667_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1981929/org.greenstand.android.treetracker_issue_22_crash_5AEE8BAE02C0000150B41ADADD100667_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device1- Moto G(4) Plus, OS- 7.0 & Device2- Huawei P8 Lite OS-6.0
App Version- Version 1.2.1 (31)
Fabric error- # 22

**Comment by deepwinter** [comment]
Looks like Async task might still be running after the app closes or starts to close, leading to this error message.
