### ISSUE TITLE
DatabaseManager - org.greenstand.android.TreeTracker.database.DatabaseManager.openDatabase(2 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#98]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase org.greenstand.android.TreeTracker.database.DbHelper.getWritableDatabase()' on a null object reference
       at org.greenstand.android.TreeTracker.database.DatabaseManager.openDatabase(Unknown Source)
       at org.greenstand.android.TreeTracker.fragments.DataFragment.updateData(Unknown Source)
       at org.greenstand.android.TreeTracker.fragments.DataFragment.onResume(Unknown Source)
       at android.support.v4.app.Fragment.performResume(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.addOp(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.executeOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_4_crash_5AFC28EF036E00016637AE6E0F782490_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2019966/org.greenstand.android.treetracker_issue_4_crash_5AFC28EF036E00016637AE6E0F782490_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device1- Infinix X572, OS- 7.0 & Device2- Galaxy J1 Ace OS-4.4.4
App Version- Version 1.2.1 (31)
Fabric error- # 4

**Comment by Surbhi79** [comment]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase org.greenstand.android.TreeTracker.database.DbHelper.getWritableDatabase()' on a null object reference

**Comment by deepwinter** [comment]
Closing this out.  I believe the new 	
`public static DbHelper getDbHelper(Context context){`

resolves this issue
