### ISSUE TITLE
 DbHelper - org.greenstand.android.TreeTracker.database.DbHelper.createDataBase(14 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#99]
Fatal Exception: java.lang.Error: Error copying database
       at org.greenstand.android.TreeTracker.database.DbHelper.createDataBase(Unknown Source)
       at org.greenstand.android.TreeTracker.activities.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Surbhi79** [comment]
Device1- Moto C Plus, OS- 7.0
App Version- Version 1.2.1 (31)
Fabric error- # 26

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker_issue_26_crash_5AF516C401E100012770B387D6B3D932_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2019974/org.greenstand.android.treetracker_issue_26_crash_5AF516C401E100012770B387D6B3D932_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
This error will be thrown when the path is wrong.  We are not dynamically calculating the path, so that's probably the issue.
